sudo: required

language: bash

env:
  matrix:
    - TEST_NAME=waterauth
    - TEST_NAME=gateway
    - TEST_NAME=ddot
    - TEST_NAME=legacycru
    - TEST_NAME=notification
    - TEST_NAME=transformer
    - TEST_NAME=validator
    - TEST_NAME=wscfileexporter
  global:
    - DOCKER_COMPOSE_VERSION=1.23.2

services:
  - docker

cache:
  bundler: true
  directories:
    - $HOME/docker

stages:
  - precache
  - test

jobs:
  include:
    - stage: precache
      before_install: true
      install:
        - mkdir -p $HOME/docker
        - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        - find . -name "*.sh" -exec chmod +x {} \;
        - sudo mv docker-compose /usr/local/bin
      script:
        - ./.travis/load_images.sh
        - ./pull-containers.sh
        - ./.travis/save_images.sh

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - find . -name "*.sh" -exec chmod +x {} \;
  - sudo mv docker-compose /usr/local/bin
install:
  - ./.travis/load_images.sh
script:
  - ./launch_services.sh
  - ./launch_jmeter_servers.sh
  - echo "Testing ${TEST_NAME}"
  - ./tests/integrations/${TEST_NAME}/test_plan.sh
  - echo "Reading results for ${TEST_NAME}"
  - ./read_results.sh $TEST_NAME
