sudo: required

language: bash

services:
  - docker

cache:
  directories:
    - $HOME/docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.23.2
  # matrix:
  #   - TEST_NAME=waterauth
  #   - TEST_NAME=gateway
  #   - TEST_NAME=ddot
  #   - TEST_NAME=legacycru
  #   - TEST_NAME=notification
  #   - TEST_NAME=transformer
  #   - TEST_NAME=validator
  #   - TEST_NAME=wscfileexporter

stages:
  - precache
  - test



jobs:
  include:
    - stage: precache
      before_install: true
      install:
        - echo "INSTALL IN PRECACHE"
      script:
        - echo "SCRIPT IN PRECACHE"
        - echo "PRECACHE JOB" > $HOME/docker/cache
    - &test
      stage: test
      before_install:
        - echo "BEFORE INSTALL IN TEST"
      install:
        - echo "INSTALL IN TEST"
      script:
        - echo "SCRIPT IN TEST"
        - cat $HOME/docker/cache
    - <<: *test
      script: echo "TEST WATERAUTH"
    - <<: *test
      script: echo "TEST GATEWAY"
    - <<: *test
      script: echo "TEST DDOT"
