sudo: required

env:
  matrix:
    - TEST_NAME='waterauth'
    - TEST_NAME='gateway'
  global:
    - DOCKER_COMPOSE_VERSION=1.23.2

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

cache:
  bundler: true
  directories:
    - $HOME/docker

jobs:
  include:
    - stage: prepare cache
      before_cache:
        # Save tagged docker images
        - mkdir -p $HOME/docker
        - docker pull nginx
        - docker save nginx:latest -o $HOME/docker/nginx.tar
      script:
        - echo "HELLO"
      before_install:
        - sudo apt-get update
        - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
        - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
        - chmod +x *.sh
        - sudo service postgresql stop
        - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
        - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
      install:
        - docker pull nginx:latest
    - stage: test
      script:
        - docker image ls
