sudo: required

language: bash

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.23.2

services:
  - docker

cache:
  bundler: true
  directories:
    - $HOME/docker

stages:
  - precache
  - test

_test: &_test
  stage: test
  before_install:
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin
    - find . -type f -iname "*.sh" -exec chmod +x {} \;
  install:
    - ./.travis/load_images.sh;
  script:
    - echo "Launching services"
    - ./launch_services.sh
    - ./launch_jmeter_servers.sh

jobs:
  include:
    - stage: precache
      before_install:
        - find . -type f -iname "*.sh" -exec chmod +x {} \;
      install:
        - mkdir -p $HOME/docker
        - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
      script:
        - ./.travis/load_images.sh
        - ./pull-containers.sh
        - ./.travis/save_images.sh
    - <<: *_test
      name: waterauth
      script: ./tests/integrations/waterauth/test_plan.sh && ./read_results.sh waterauth
    - <<: *_test
      name: gateway
      script: ./tests/integrations/gateway/test_plan.sh && ./read_results.sh gateway
    - <<: *_test
      name: ddot
      script: ./tests/integrations/ddot/test_plan.sh && ./read_results.sh ddot
    - <<: *_test
      name: legacycru
      script: ./tests/integrations/legacycru/test_plan.sh && ./read_results.sh legacycru
    - <<: *_test
      name: notification
      script: ./tests/integrations/notification/test_plan.sh && ./read_results.sh notification
    - <<: *_test
      name: transformer
      script: ./tests/integrations/transformer/test_plan.sh && ./read_results.sh transformer
    - <<: *_test
      name: validator
      script: ./tests/integrations/validator/test_plan.sh && ./read_results.sh validator
    - <<: *_test
      name: wscfileexporter
      script: ./tests/integrations/wscfileexporter/test_plan.sh && ./read_results.sh wscfileexporter
