sudo: required

language: bash

services:
  - docker

cache:
  directories:
    - $HOME/docker
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.23.2
  matrix:
    - TEST_NAME=waterauth
    - TEST_NAME=gateway
    - TEST_NAME=ddot
    - TEST_NAME=legacycru
    - TEST_NAME=notification
    - TEST_NAME=transformer
    - TEST_NAME=validator
    - TEST_NAME=wscfileexporter

stages:
  - precache
  - testz

jobs:
  include:
    - stage: precache
      before_cache:
        - mkdir -p $HOME/docker
      install:
        - echo "INSTALL"
        - echo $(date) > $HOME/docker/date.txt
    - stage: testz
      before_install:
        - echo "BEFORE INSTALL"
      install:
        - echo "INSTALL"
      script:
        - echo "SCRIPT"
