sudo: required

language: bash

env:
  matrix:
    - TEST_NAME=waterauth
    - TEST_NAME=gateway
    - TEST_NAME=ddot
    - TEST_NAME=legacycru
    - TEST_NAME=notification
    - TEST_NAME=transformer
    - TEST_NAME=validator
    - TEST_NAME=wscfileexporter
  global:
    - DOCKER_COMPOSE_VERSION=1.23.2

services:
  - docker

cache:
  bundler: true
  directories:
    - $HOME/docker

stages:
  - precache
  - test

jobs:
  include:
    - stage: precache
      install:
        - mkdir -p $HOME/docker
        - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
      script:
        - chmod +x ./.travis/load_images.sh && ./.travis/load_images.sh
        - chmod +x ./pull-containers.sh && ./pull-containers.sh
        - chmod +x ./.travis/save_images.sh && ./.travis/save_images.sh

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
install:
  - chmod +x *.sh
  - chmod +x ./.travis/load_images.sh && ./.travis/load_images.sh
  - chmod +x "./tests/integrations/${TEST_NAME}/test_plan.sh";
script:
  - echo "Launching services"
  - ./launch_services.sh
  - ./launch_jmeter_servers.sh
  - echo "Testing ${TEST_NAME}"
  - ./tests/integrations/${TEST_NAME}/test_plan.sh
  - echo "Reading results for ${TEST_NAME}"
  - ./read_results.sh $TEST_NAME
