sudo: required

language: bash

services:
  - docker

cache:
  directories:
    - $HOME/docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.23.2
  # matrix:
  #   - TEST_NAME=waterauth
  #   - TEST_NAME=gateway
  #   - TEST_NAME=ddot
  #   - TEST_NAME=legacycru
  #   - TEST_NAME=notification
  #   - TEST_NAME=transformer
  #   - TEST_NAME=validator
  #   - TEST_NAME=wscfileexporter

stages:
  - precache
  - test

_test: &_test
  stage: test
  before_install:
    - echo "BEFORE INSTALL IN TEST ALIAS "
  install:
    - echo "INSTALL IN TEST ALIAS "
  script:
    - echo "SCRIPT IN TEST ALIAS "
    - cat $HOME/docker/cache

jobs:
  include:
    - stage: precache
      before_install: true
      install:
        - echo "INSTALL IN PRECACHE"
      script:
        - echo "SCRIPT IN PRECACHE"
        - echo "PRECACHE JOB" > $HOME/docker/cache
    - <<: *_test
      name: waterauth
      script: echo "TEST WATERAUTH"
    - <<: *_test
      name: gateway
      script: echo "TEST GATEWAY"
    - <<: *_test
      name: ddot
      script: echo "TEST DDOT"
